In [139]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [140]:
loan_data = pd.read_excel(r'default of credit card clients.xls')

In [141]:
loan_data

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [142]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_A

In [143]:
loan_data.shape

(30000, 25)

In [144]:
loan_data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [145]:
y = loan_data['default payment next month'].unique()


In [146]:
y_count = loan_data['default payment next month'].value_counts()
y_count

0    23364
1     6636
Name: default payment next month, dtype: int64

In [147]:
num_col = loan_data.dtypes !='object'
num_col

ID                            True
LIMIT_BAL                     True
SEX                           True
EDUCATION                     True
MARRIAGE                      True
AGE                           True
PAY_0                         True
PAY_2                         True
PAY_3                         True
PAY_4                         True
PAY_5                         True
PAY_6                         True
BILL_AMT1                     True
BILL_AMT2                     True
BILL_AMT3                     True
BILL_AMT4                     True
BILL_AMT5                     True
BILL_AMT6                     True
PAY_AMT1                      True
PAY_AMT2                      True
PAY_AMT3                      True
PAY_AMT4                      True
PAY_AMT5                      True
PAY_AMT6                      True
default payment next month    True
dtype: bool

In [148]:
loan_data.describe()

ID       LIMIT_BAL           SEX     EDUCATION      MARRIAGE  \
count  30000.000000    30000.000000  30000.000000  30000.000000  30000.000000   
mean   15000.500000   167484.322667      1.603733      1.853133      1.551867   
std     8660.398374   129747.661567      0.489129      0.790349      0.521970   
min        1.000000    10000.000000      1.000000      0.000000      0.000000   
25%     7500.750000    50000.000000      1.000000      1.000000      1.000000   
50%    15000.500000   140000.000000      2.000000      2.000000      2.000000   
75%    22500.250000   240000.000000      2.000000      2.000000      2.000000   
max    30000.000000  1000000.000000      2.000000      6.000000      3.000000   

                AGE         PAY_0         PAY_2         PAY_3         PAY_4  \
count  30000.000000  30000.000000  30000.000000  30000.000000  30000.000000   
mean      35.485500     -0.016700     -0.133767     -0.166200     -0.220667   
std        9.217904      1.123802      1.197186      1.196868      1.169139   
min       21.000000     -2.000000     -2.000000     -2.000000     -2.000000   
25%       28.000000     -1.000000     -1.000000     -1.000000     -1.000000   
50%       34.000000      0.000000      0.000000      0.000000      0.000000   
75%       41.000000      0.000000      0.000000      0.000000      0.000000   
max       79.000000      8.000000      8.000000      8.000000      8.000000   

       ...      BILL_AMT4      BILL_AMT5      BILL_AMT6       PAY_AMT1  \
count  ...   30000.000000   30000.000000   30000.000000   30000.000000   
mean   ...   43262.948967   40311.400967   38871.760400    5663.580500   
std    ...   64332.856134   60797.155770   59554.107537   16563.280354   
min    ... -170000.000000  -81334.000000 -339603.000000       0.000000   
25%    ...    2326.750000    1763.000000    1256.000000    1000.000000   
50%    ...   19052.000000   18104.500000   17071.000000    2100.000000   
75%    ...   54506.000000   50190.500000   49198.250000    5006.000000   
max    ...  891586.000000  927171.000000  961664.000000  873552.000000   

           PAY_AMT2      PAY_AMT3       PAY_AMT4       PAY_AMT5  \
count  3.000000e+04   30000.00000   30000.000000   30000.000000   
mean   5.921163e+03    5225.68150    4826.076867    4799.387633   
std    2.304087e+04   17606.96147   15666.159744   15278.305679   
min    0.000000e+00       0.00000       0.000000       0.000000   
25%    8.330000e+02     390.00000     296.000000     252.500000   
50%    2.009000e+03    1800.00000    1500.000000    1500.000000   
75%    5.000000e+03    4505.00000    4013.250000    4031.500000   
max    1.684259e+06  896040.00000  621000.000000  426529.000000   

            PAY_AMT6  default payment next month  
count   30000.000000                30000.000000  
mean     5215.502567                    0.221200  
std     17777.465775                    0.415062  
min         0.000000                    0.000000  
25%       117.750000                    0.000000  
50%      1500.000000                    0.000000  
75%      4000.000000                    0.000000  
max    528666.000000                    1.000000  

[8 rows x 25 columns]

In [149]:
corrMatrix = loan_data.corr(method = 'pearson')
corrMatrix

ID  LIMIT_BAL       SEX  EDUCATION  \
ID                          1.000000   0.026179  0.018497   0.039177   
LIMIT_BAL                   0.026179   1.000000  0.024755  -0.219161   
SEX                         0.018497   0.024755  1.000000   0.014232   
EDUCATION                   0.039177  -0.219161  0.014232   1.000000   
MARRIAGE                   -0.029079  -0.108139 -0.031389  -0.143464   
AGE                         0.018678   0.144713 -0.090874   0.175061   
PAY_0                      -0.030575  -0.271214 -0.057643   0.105364   
PAY_2                      -0.011215  -0.296382 -0.070771   0.121566   
PAY_3                      -0.018494  -0.286123 -0.066096   0.114025   
PAY_4                      -0.002735  -0.267460 -0.060173   0.108793   
PAY_5                      -0.022199  -0.249411 -0.055064   0.097520   
PAY_6                      -0.020270  -0.235195 -0.044008   0.082316   
BILL_AMT1                   0.019389   0.285430 -0.033642   0.023581   
BILL_AMT2                   0.017982   0.278314 -0.031183   0.018749   
BILL_AMT3                   0.024354   0.283236 -0.024563   0.013002   
BILL_AMT4                   0.040351   0.293988 -0.021880  -0.000451   
BILL_AMT5                   0.016705   0.295562 -0.017005  -0.007567   
BILL_AMT6                   0.016730   0.290389 -0.016733  -0.009099   
PAY_AMT1                    0.009742   0.195236 -0.000242  -0.037456   
PAY_AMT2                    0.008406   0.178408 -0.001391  -0.030038   
PAY_AMT3                    0.039151   0.210167 -0.008597  -0.039943   
PAY_AMT4                    0.007793   0.203242 -0.002229  -0.038218   
PAY_AMT5                    0.000652   0.217202 -0.001667  -0.040358   
PAY_AMT6                    0.003000   0.219595 -0.002766  -0.037200   
default payment next month -0.013952  -0.153520 -0.039961   0.028006   

                            MARRIAGE       AGE     PAY_0     PAY_2     PAY_3  \
ID                         -0.029079  0.018678 -0.030575 -0.011215 -0.018494   
LIMIT_BAL                  -0.108139  0.144713 -0.271214 -0.296382 -0.286123   
SEX                        -0.031389 -0.090874 -0.057643 -0.070771 -0.066096   
EDUCATION                  -0.143464  0.175061  0.105364  0.121566  0.114025   
MARRIAGE                    1.000000 -0.414170  0.019917  0.024199  0.032688   
AGE                        -0.414170  1.000000 -0.039447 -0.050148 -0.053048   
PAY_0                       0.019917 -0.039447  1.000000  0.672164  0.574245   
PAY_2                       0.024199 -0.050148  0.672164  1.000000  0.766552   
PAY_3                       0.032688 -0.053048  0.574245  0.766552  1.000000   
PAY_4                       0.033122 -0.049722  0.538841  0.662067  0.777359   
PAY_5                       0.035629 -0.053826  0.509426  0.622780  0.686775   
PAY_6                       0.034345 -0.048773  0.474553  0.575501  0.632684   
BILL_AMT1                  -0.023472  0.056239  0.187068  0.234887  0.208473   
BILL_AMT2                  -0.021602  0.054283  0.189859  0.235257  0.237295   
BILL_AMT3                  -0.024909  0.053710  0.179785  0.224146  0.227494   
BILL_AMT4                  -0.023344  0.051353  0.179125  0.222237  0.227202   
BILL_AMT5                  -0.025393  0.049345  0.180635  0.221348  0.225145   
BILL_AMT6                  -0.021207  0.047613  0.176980  0.219403  0.222327   
PAY_AMT1                   -0.005979  0.026147 -0.079269 -0.080701  0.001295   
PAY_AMT2                   -0.008093  0.021785 -0.070101 -0.058990 -0.066793   
PAY_AMT3                   -0.003541  0.029247 -0.070561 -0.055901 -0.053311   
PAY_AMT4                   -0.012659  0.021379 -0.064005 -0.046858 -0.046067   
PAY_AMT5                   -0.001205  0.022850 -0.058190 -0.037093 -0.035863   
PAY_AMT6                   -0.006641  0.019478 -0.058673 -0.036500 -0.035861   
default payment next month -0.024339  0.013890  0.324794  0.263551  0.235253   

                               PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  \
ID

# applying machine learning model

In [150]:
loan_data_num = loan_data.loc[:,num_col]
loan_data_num.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [151]:
features = loan_data_num.columns != 'default payment next month'
target = loan_data_num.columns == 'default payment next month'
X = loan_data_num.iloc[:, features]
y = loan_data_num.iloc[:, target]

In [152]:
features

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False])

In [153]:
target

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True])

In [154]:
from sklearn.model_selection import train_test_split

In [155]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3,random_state = 1)

In [156]:
y_train['default payment next month'].value_counts()

0    16364
1     4636
Name: default payment next month, dtype: int64

In [157]:
y_test['default payment next month'].value_counts()

0    7000
1    2000
Name: default payment next month, dtype: int64

In [158]:
y_train = y_train.values.ravel()
y_train.shape

(21000,)

In [159]:
from sklearn.dummy import DummyClassifier

In [160]:
dummy_clf = DummyClassifier(strategy = 'uniform', random_state = 1)
dummy_clf.fit(X_train,y_train)

DummyClassifier(constant=None, random_state=1, strategy='uniform')

In [161]:
training_score = dummy_clf.score(X_train,y_train)
testing_score = dummy_clf.score(X_test,y_test)

In [162]:
training_score

0.5072380952380953

In [163]:
testing_score

0.5034444444444445

In [164]:
from sklearn.linear_model import LinearRegression, LogisticRegression

In [165]:
lr_clf = LogisticRegression(max_iter = 500)
lr_model = lr_clf.fit(X_train,y_train)

In [166]:
lr_model.coef_ 

array([[-1.13196541e-05, -2.91888190e-06, -9.14250652e-04,
        -1.03710372e-03, -1.01226681e-03, -1.31421266e-02,
         2.52894863e-03,  2.00941270e-03,  1.70965752e-03,
         1.58628579e-03,  1.41123623e-03,  1.28608911e-03,
        -7.50890722e-06,  4.82540069e-06,  6.34476726e-07,
         2.87746261e-06,  1.58185264e-06,  2.18284884e-06,
        -2.94135272e-05, -1.57250589e-05, -8.78797349e-06,
        -8.80386080e-06, -6.80599143e-06, -2.21298764e-06]])

In [167]:
lr_model.intercept_

array([-0.00049001])

In [168]:
lr_prediction = lr_model.predict(X_test)
trainScore = lr_model.score(X_train,y_train)
testScore = lr_model.score(X_test,y_test)

In [169]:
trainScore

0.7792380952380953

In [170]:
testScore

0.7777777777777778

In [171]:
from sklearn.tree import DecisionTreeClassifier, _criterion

In [172]:
decisiontree = DecisionTreeClassifier(random_state = 0)
DT_model = decisiontree.fit(X_train,y_train)
DT_prediction = DT_model.predict(X_test)

In [173]:
DT_model.score(X_train,y_train)
DT_model.score(X_test,y_test)

0.7186666666666667

In [174]:
DT_model.score(X_train,y_train)

1.0

In [175]:
decisiontree = DecisionTreeClassifier(criterion = 'entropy',  random_state = 0)
DT_model = decisiontree.fit(X_train,y_train)

In [176]:
DT_model.score(X_train,y_train)

1.0

In [177]:
DT_model.score(X_test,y_test)

0.7283333333333334

In [178]:
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 15, max_features = 0.3, random_state = 1)
forest.fit(X_train,y_train)
forest_pred = forest.predict(X_test)

In [179]:
forest.score(X_train,y_train)

0.9930952380952381

In [180]:
forest.score(X_test,y_test)

0.8086666666666666

In [181]:
from sklearn.metrics import confusion_matrix

In [182]:
ConfMatrix = confusion_matrix(y_test,forest_pred)
ConfMatrix

array([[6546,  454],
       [1268,  732]], dtype=int64)

In [183]:
ConfMatrix = confusion_matrix(y_test,lr_prediction)
ConfMatrix

array([[7000,    0],
       [2000,    0]], dtype=int64)

In [184]:
ConfMatrix = confusion_matrix(y_test,DT_prediction)
ConfMatrix

array([[5642, 1358],
       [1174,  826]], dtype=int64)

In [193]:
from sklearn.metrics import confusion_matrix,classification_report,roc_auc_score,roc_curve

In [197]:
from sklearn.metrics import classification_report  

In [199]:
print(classification_report(y_test,forest_pred))

              precision    recall  f1-score   support

           0       0.84      0.94      0.88      7000
           1       0.62      0.37      0.46      2000

    accuracy                           0.81      9000
   macro avg       0.73      0.65      0.67      9000
weighted avg       0.79      0.81      0.79      9000



In [200]:
TP = 6546
TN = 732
FP = 1268
FN = 454

In [202]:
recall = TP/(TP+FN)
recall

0.9351428571428572

In [203]:
precision = TP/(TP+FP)
precision

0.837727156385974

In [204]:
f1_score = (precision * recall / (precision + recall))* 2
f1_score

0.8837586067233698